### PR TITLE
Add vector comparisons

### PR DESCRIPTION
**Pull request by chorman0773**
This allows comparing Vector elements

### CODE REVIEW

**Comment by rdrpenguin04** [comment]
Instructions need to be added to `machine-tables`

**Review by rdrpenguin04 — COMMENTED** [review]
Suggestion: You have two free h bits; you could use them to select the test you do instead of making more opcodes. Unless you wanted to reserve them of course.

**Comment by chorman0773** [comment]
At one bit is reserved for larger element sizes (when combined with a
larger vector size).

**Comment by rdrpenguin04** [comment]
Alright

**Review by rdrpenguin04 — APPROVED** [review]
LGTM

**Comment by chorman0773** [comment]
Waiting on a way to turn the flags result into a mask or otherwise allow conditional movement

**Comment by chorman0773** [comment]
Unblocks finalization when #44 is approved.

**Pull request merged**
